# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todotask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=500)),
                ('taskDescription', models.TextField()),
                ('addedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('taskStatus', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('hidestatus', models.CharField(choices=[('1', 'Show'), ('0', 'Hide')], default='1', max_length=20)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
